services:
  redish:
    container_name: redish
    image: redish:latest
    depends_on:
      - redis-db
    ports:
      - 8989:8989
    networks:
      redish-network:
  redis-db:
    image: 'redis:alpine3.18'
    ports:
      - 6363:6379

networks:
  redish-network:
    name: redish-net
